### ISSUE TITLE
Documentation update for using opts

### ISSUE THREAD

**Issue by mattgia** [Pop-Code/nestjs-console#311]
**Is your feature request related to a problem? Please describe.**
Documentation suggests to use command.opts() to retrieve command options, but actual behavior is that commands are available directly on the command object, i.e. command.opt1

You can still access the commander object, but that comes after the options object. See the last example

**Describe the solution you'd like**
Update documentation to reflect real usage.

**Describe alternatives you've considered**
N/A

**Additional context**
This doesn't work
```javascript
@Command({
        command: 'create <email>',
        description: 'Create a new user',
        options: [
            {
                flags: '--firstName <firstNameValue>',
                required: false
            },
        ]
    })
    async create(email: string, command): Promise<void> {
       command.opts() // opts is not a function
}
```
This works
```javascript
@Command({
        command: 'create <email>',
        description: 'Create a new user',
        options: [
            {
                flags: '--firstName <firstNameValue>',
                required: false
            },
        ]
    })
    async create(email: string, options, commander): Promise<void> {
         options.firstName // works
         commander.opts().firstName //works

}
```

NestJS 7.6.13
nestjs-console 4.0.0

**Comment by Rmannn** [comment]
What is the version of commander you re using ?

Options as properties should be disabled in https://github.com/Pop-Code/nestjs-console/blob/cea8cf72ff8a4b5cbe044caeb750608d1d153840/src/service.ts#L157

A PR is open an need more test to use the last version of commander.
Code was simplified to do not hack commander.

**Comment by mattgia** [comment]
I'm using commander 7.2.0

**Comment by Rmannn** [comment]
Can you try using the 6.2.0 ? If it works as expected, I will update the docs to fix the commander version until we publish the next release.

**Comment by mattgia** [comment]
Yep! Seems to work fine with 6.2.0.

Sorry, I guess I missed the warning that I had the wrong peer dependency installed. Thanks for your help!

**Comment by Rmannn** [comment]
You're welcome.
Don't worry, I should have updated the doc. That's done.  I close the issue.
