### ISSUE TITLE
TypeError: parent.addCommand is not a function

### ISSUE THREAD

**Issue by amit-sharma-dev** [Pop-Code/nestjs-console#375]
I am getting this error while running the command from the terminal.
It is coming on createCommand() function.

```
this.consoleService.createCommand(
      {
        command: this.updateSubscription.command,
        description: this.updateSubscription.description,
      },
      this.updateSubscription.run,
      cli
    );
```

am I missing something? please suggest.

Versions: 
node: v12.22.6
npm: 6.14.15
"@nestjs/core": "^7.0.0"
"@nestjs/common": "^7.0.0"

**Comment by Rmannn** [comment]
What is the version of commander ? Also last version of nestjs-console is test with nestjs 8

**Comment by amit-sharma-dev** [comment]
> What is the version of commander ? Also last version of nestjs-console is test with nestjs 8

"nestjs-console": "^3.0.5"

**Comment by Rmannn** [comment]
I suppose your using a version of commander that is too recent and a version of nestjs console that is too old.

Nestjs console is up to date to work with nestjs 8 and commander 7.

Try to upgrade.

**Comment by amit-sharma-dev** [comment]
> I suppose you are using a version of commander that is too recent and a version of nestjs console that is too old.
> 
> Nestjs console 7 is up to date to work with nestjs 8 and commander 8.
> 
> Try to upgrade.

This is working with version 2.1.0

**Comment by amit-sharma-dev** [comment]
issue resolved
